```yaml
name: Backend CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Connect to AMD server and deploy
      - name: Deploy to atlviqaapd01
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: atlviqaapd01
          username: epoh
          password: Peq2111###
          script: |
            cd /opt/amd-iqa/backend
            git pull origin main
            /usr/bin/sudo systemctl restart amd-iqa-backend
```
